### ISSUE TITLE
Bug: Issues with fast/slow in Traits

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#15]
When you have fast or slow in your traits list and select the opposite trait from the dropdown the original is not removed and the new trait is not added

Reproduction steps:
Add Fast to traits
hit + to max out the value (optional)
Add Slow to traits

Slow is not added to the traits and fast is not removed

**Comment by oldschoolbg** [comment]
This "replace" feature was removed while fixing #10 as it caused an inconsistency with the behaviour.

Now you'll get an error when you try to do the above.

**Comment by Dunfee** [comment]
closing after discussion yesterday
