### ISSUE TITLE
Research: Investigate displaying commander warning message in another way

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#17]
As per our discord conversation

Ryan — Today at 4:34 PM
trying to think up new options for the "You cannot set an Instinct character as your Commander" and "You cannot change a Commander from Regular" messages. I always thought it was weird to show that even when you have not triggered the error trying to do what you're not allowed to do
thebeard — Today at 4:42 PM
it's a message explaining why the option is disabled
it isn't an error
Ryan — Today at 4:42 PM
yeah, I think the red text is throwing me off.
or red area.
red always makes me think "Oh I've fucked up somewhere"
I wonder if we could have a question mark icon next to them and if you click it or tap it on mobile the description pops up for a few seconds
or until you dismiss it
thebeard — Today at 4:46 PM
yeah fair point :slight_smile:
pop an issue in and i'll have a look at those options

**Comment by oldschoolbg** [comment]
I've updated the message and the colour for this - let me know!

**Comment by Dunfee** [comment]
New look makes the area look much cleaner. Closing!
