### ISSUE TITLE
Bug: Misc equipment fixes

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#18]
A few issues with the misc equipment section
Spellcasting implements, spellbooks/scrolls should be able to be brought by anyone, not just spellcasters. This allows them to hand off that item to prisoners in the case of scenarios where your goal is to rescue a character. Currently they are not in the dropdown if the spellcaster trait is not present.

Bells/Horn/Drums can be one item instead of 3 with the player choosing what their item looks like.

Rename trinkets to trinket

**Comment by oldschoolbg** [comment]
fixed in most recent commit.
