### ISSUE TITLE
Typo: Mixed English and American spellings

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#6]
Mostly Armor vs Armour. The book has American spellings so it would be nice to keep that consistent

**Comment by oldschoolbg** [comment]
**has an idea**

Why doesn't the book spell it correctly? ;)

HAHA :) I'm gonna change it don't worry...

*grumbles about spelling in yank*

**Comment by oldschoolbg** [comment]
fixed in next version
