### ISSUE TITLE
Suggestion: Pop skills out of dropdown list when already applied or not available

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#8]
This is a nice to have. Would be great to remove skills from the dropdown list if they are already assigned to the character. Would make navigating the rest of the skills easier.

**Comment by oldschoolbg** [comment]
Good idea.

I also plan to remove Skills that are not available to the Character for some reason.

**Comment by oldschoolbg** [comment]
available to test in the next version

**Comment by oldschoolbg** [comment]
resolved in latest version
