### ISSUE TITLE
Clarity: Prerequisites fail only in console

### ISSUE THREAD

**Issue by Dunfee** [oldschoolbg/anthems-of-war-character-builder#9]
No feedback when bad combos are added to the page. Example: Adding latent spellcaster and then trying to add versatile spellcaster. Console error message appears but no on screen messages

**Comment by oldschoolbg** [comment]
The error handling is yet to be implemented.

This will either be done via a toast alert or inline.

To be agreed.

**Comment by oldschoolbg** [comment]
Errors show up in toasts
